spring.application.name=demo
server.port=7878

#spring.datasource.url="jdbc:oracle:thin:@//localhost:1521/mydb"

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.security.user.name=admin
spring.security.user.password=1234